### ISSUE TITLE
Channel options not being applied

### ISSUE THREAD

**Issue by darwin67** [sous-chefs/orbs#10]
# Brief Description

The `channel` parameter in the orb is always `current` regardless of what value you're setting since it never gets applied

## version

master, HEAD

## Platform Details

CircleCI

## Scenario

Trying to use this `orb` on CircleCI

## Steps to Reproduce

add the `channel` param on `dokken-single` or `dokken`, and you'll see `current` is the value that always get used when you look at the logs

## Expected Result

It should use the version I specified for chefdk or chef-client

## Actual Result

![chef](https://user-images.githubusercontent.com/5746693/53863638-8974e480-3f9f-11e9-9c40-622b42b586e4.png)

**Comment by damacus** [comment]
Hey, thanks for using the orb. Could you try dev:fist for me 
`sous-chefs/kitchen@dev:first`

https://github.com/sous-chefs/orbs/pull/11

**Comment by darwin67** [comment]
Got it! I'll test it out soon!

**Comment by darwin67** [comment]
@damacus hey, thanks for the quick response!
confirmed that `sous-chefs/kitchen@dev:first` fixed it!

https://circleci.com/gh/darwin67/chef-pyenv/127?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by darwin67** [comment]
would you mind sharing the latest version when you release it?
thanks!
