### ISSUE TITLE
Package Lock In CircleCI

### ISSUE THREAD

**Issue by damacus** [sous-chefs/orbs#20]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

When we run 

## :pancakes: Cookbook version

Version of the cookbook where you are encountering the issue.

## :woman_cook:  Chef-Infra Version

Version of chef-client in your environment.

## :tophat: Platform details

Operating system distribution and release version. Cloud provider if running in the cloud.

## Steps To Reproduce

Start a CircleCI job

## :police_car: Expected behaviour

Jobs don't get locked via a running CircleCI unattended upgrade process

**Comment by damacus** [comment]
CircleCI support suggested this article

https://support.circleci.com/hc/en-us/articles/360021256633-Apt-Get-Update-Is-Slow-Or-Locked?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo4MjgyMDksInVzZXJfaWQiOjM4OTkyNzg2MzQ3MywidGlja2V0X2lkIjo1Njk1NCwiY2hhbm5lbF9pZCI6NjMsInR5cGUiOiJTRUFSQ0giLCJleHAiOjE1NzEyMzIyNzd9.ORGxIuGnE4hPr5xAWY4QAkXECliKV9CGNTQPASqaBaQ

**Comment by PowerSchill** [comment]
I assume that would have to be fixed in the orb?

**Comment by damacus** [comment]
Yeah, as the ChefDK install is part of the orb it needs fixing there.

**Comment by PowerSchill** [comment]
It doesn't look like we are doing anything other than `dpkg` with chef so what is locking it beforehand.

**Comment by damacus** [comment]
Closed thanks to @PowerSchill's work on digging through the docs
